Hw2
de-brasi/tinkoff-education-java-backend-tasks-spring pull request #3
Opened 2024-02-23 19:04 UTC by de-brasi

2024-02-28 17:02 UTC, edikgoose requested changes
Задание выполнено, все ок
Советую проставить таймауты (значения тянуть из конфига) и ретраи на запрос и в целом почитать про паттерны отказоустойчивости. Будет полезным для собесов

И еще все-таки крайне советую переделать архитектуру с первого задания под спринговую

6/6

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +        GitHubClient githubClient =
Этот код для чего нужен?)

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +        Pattern dateSearchPattern = Pattern.compile(
Я бы вынес это как минимум в отдельную функцию

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
>      Scheduler scheduler
Лучше создать отдельный класс с @ConfigurationProperties(prefix = "app.scheduler")

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/test/java/edu/java/scrapper/ClientTestConfig.java
> +    @Bean("testGitHubClient")
В спринге есть аннотация @TestConfiguration. Ее ты можешь вот так добавить @SpringBootTest(classes = TestConfig.class) в тесты
Текущее решение чутка костыльное)

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +    public GitHubClient gitHubClient(@Autowired RestClient.Builder builder) {
Лучше свой билдер создать в каждом клиенте и прописать параметры таймаутов для каждого из клиента

2024-02-28 17:02 UTC, edikgoose commented on scrapper/src/test/java/edu/java/scrapper/GitHubClientTest.java
> +    public void test1() {
тесты лучше называть с семантическим смыслом

2024-03-11 15:18 UTC, de-brasi commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +        GitHubClient githubClient =
Упс, писал для того чтобы проверить работоспособность до того как сделал тесты)

2024-03-11 15:22 UTC, de-brasi commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
>      Scheduler scheduler
Не очень понял как это? Создать класс и потом заинжектить его в ApplicationConfig через @Autowired? Или вообще удалить все что касается планировщика из ApplicationConfig и создать отдельный конфиг класс для него?

2024-03-11 18:34 UTC, de-brasi commented on scrapper/src/test/java/edu/java/scrapper/GitHubClientTest.java
> +    public void test1() {
Если есть говорящее описание в DisplayName, то не будет это избыточным?

2024-03-11 18:48 UTC, de-brasi commented on scrapper/src/test/java/edu/java/scrapper/GitHubClientTest.java
> +    public void test1() {
P.S поправил

2024-03-11 18:50 UTC, de-brasi commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +        Pattern dateSearchPattern = Pattern.compile(
Сделал

2024-03-11 18:50 UTC, de-brasi commented on scrapper/src/test/java/edu/java/scrapper/ClientTestConfig.java
> +    @Bean("testGitHubClient")
Сделал

2024-03-11 18:50 UTC, de-brasi commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +    public GitHubClient gitHubClient(@Autowired RestClient.Builder builder) {
Сделал

2024-03-11 18:56 UTC, de-brasi commented
Не смог найти как реализовать механизм ретраев встроенными методами. Есть какой то изящный способ для RestClient или просто делать цикл на несколько итераций пока не выполнится запрос? Кажется проблемой что при таком подходе на блокирующих клиентах (ну, которые не реактивные) не получится делать повторные попытки запросов через интервалы времени без блокировки потока

2024-03-13 17:03 UTC, merged